where_indent = "Tabbed"
where_pred_indent = "Tabbed"
generics_indent = "Tabbed"
fn_arg_indent = "Tabbed"
fn_args_layout = "Block"
struct_lit_style = "Block"
chain_base_indent = "Tabbed"
chain_indent = "Tabbed"
