[package]
name = "brain"
version = "0.1.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Compiler for the brain programming language. Compiles brain into optimized brainfuck code."

[dependencies]
clap = "^2.0"

[dependencies.nom]
version = "^2.0"
features = ["verbose-errors"]

[[bin]]
name = "brain"
doc = false
